#ifndef _SNOW_CORE_CONFIG_IN_H_
#define _SNOW_CORE_CONFIG_IN_H_

#define SNOWEM_PREFIX_PATH "@SNOWEM_PREFIX_PATH@"
#define GIT_BRANCH "@GIT_BRANCH@"
#define GIT_COMMIT_HASH "@GIT_COMMIT_HASH@"

#endif // _SNOW_CORE_CONFIG_IN_H_
